//Action Types
export const ADD_NEW_ARGUMENT = 'ADD_NEW_ARGUMENT'
export const UPDATE_ARGUMENT_VALUE = 'UPDATE_ARGUMENT_VALUE'
export const GET_CHART_DATA = 'GET_CHART_DATA'
export const UPDATE_CHART_DATA = 'UPDATE_CHART_DATA'
export const GET_CHART_DATA_BY_NETLIST = 'GET_CHART_DATA_BY_NETLIST'